[package]
name = "funksyscore"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1" }
dirs = "6.0.0"
ron = "0.11.0"
log = "0.4"
serde = { version = "1", features = ["derive"] }

[features]
default = ["fast-compile"]
fast-compile = ["bevy/dynamic_linking"]
